name: Dani Dev Blog
markdown: redcarpet
pygments: true
include: ['.htaccess']
keep_files: ['.git','.svn']
baseurl: /danidev

# Third Party Plugin - RSS Generator
name: Dani Dev Blog
url: http://danielabar.github.io/danidev
description: A developers blog
author: Daniela Baron
copyright: The MIT License (MIT) Copyright (c) 2014 Daniela Baron
